backend:
  name: git-gateway
site_url: https://jeangelique.com
display_url: https://jeangelique.com/surprise
publish_mode: editorial_workflow
media_folder: static/images
public_folder: /images
slug:
  encoding: ascii
  clean_accents: true

collections:
  - name: moments
    label: Moment
    summary: '{{author}} · {{title}}'
    folder: src/pages/moments
    slug: '{{year}}-{{month}}-{{slug}}'
    create: true
    preview_path: moments/{{slug}}
    fields:
      - { name: title, label: Title }
      - {
          name: who,
          label: Who?,
          widget: select,
          options: [Angélique, Jens, Jeangelique],
        }
      - { name: author, label: Author }
      - { name: date, label: Date, widget: date, format: DD MMM YYYY }
      - { name: image, label: Cover image, widget: image, required: false }
      - { name: body, label: Body, widget: markdown }
