backend:
  name: git-gateway
site_url: https://jeangelique.com
display_url: https://jeangelique.com/surprise
publish_mode: editorial_workflow
media_folder: static/images
public_folder: /images
slug:
  encoding: ascii
  clean_accents: true

collections:
  - label: Souvenirs
    label_singular: Souvenir
    name: souvenirs
    summary: '{{author}} · {{title}}'
    create: true
    delete: false
    folder: src/pages/souvenirs
    # slug: '{{year}}-{{month}}-{{slug}}'
    preview_path: souvenirs/{{slug}}
    fields:
      - label: Author (you)
        name: author
      - label: Title
        name: title
      - label: With who?
        name: who
        widget: select
        options: [Angélique, Jens, Jeangelique]
      - label: Date
        name: date
        widget: date
        default: ''
        format: DD MMM YYYY
      - label: Place
        name: location
        widget: object
        fields:
          - label: City
            name: city
          - label: Country
            name: country
      - label: Picture
        name: image
        widget: image
        required: false
      - label: Story
        name: body
        widget: markdown
        required: false
